export const dashboardData = {
  meta: {
    cycle: "Jun '26",
    generated: "9 June 2026",
    participation: 42,
    total: 58,
    participationPct: 72,
  },
  overallScore: 3.8,
  previousScore: 3.7,
  status: "Stable" as const,
  leadershipReadout:
    "Team sentiment is stable at 3.8/5, up 0.1 from Apr '26. Ways of Working showed the biggest improvement this pulse (+0.4). Workload & Sustainability has been flagged for 3 consecutive pulses — a commitment to review sprint capacity is currently In Progress.",
  atAGlance: {
    overallStatus: { label: "Stable", score: "3.8 / 5" },
    strongestArea: { label: "Team Climate & Safety", score: "4.4" },
    needsAttention: { label: "Workload & Sustainability", score: "3.1" },
  },
  focusPulse: {
    area: "Workload & Sustainability",
    score: 3.2,
    suggestion: "Review sprint capacity and backlog prioritisation",
    pulseCount: 3,
  },
  areaMovement: [
    { name: "Ways of Working", delta: 0.4, direction: "up" },
    { name: "Value", delta: 0.1, direction: "up" },
    { name: "Direction", delta: 0.4, direction: "up" },
    { name: "Collaboration", delta: 0.1, direction: "up" },
    { name: "Workload", delta: 0.2, direction: "up" },
    { name: "Ownership", delta: 0.1, direction: "up" },
    { name: "Climate", delta: 0.2, direction: "up" },
  ],
  participationTrend: [
    { pulse: "Oct '25", count: 42 },
    { pulse: "Dec '25", count: 48 },
    { pulse: "Feb '26", count: 45 },
    { pulse: "Apr '26", count: 47 },
    { pulse: "Jun '26", count: 44 },
  ],
  pulseHistory: [
    { pulse: "Oct '25", score: 3.5 },
    { pulse: "Dec '25", score: 3.6 },
    { pulse: "Feb '26", score: 3.7 },
    { pulse: "Apr '26", score: 3.7 },
    { pulse: "Jun '26", score: 3.8 },
  ],
  areaScores: [
    { name: "Direction", score: 4.1 },
    { name: "Value", score: 3.9 },
    { name: "Ownership", score: 3.7 },
    { name: "Ways", score: 4.0 },
    { name: "Collab", score: 4.2 },
    { name: "Workload", score: 3.2 },
    { name: "Climate", score: 4.4 },
  ],
  sentiment: [
    { area: "Direction & Priorities", positive: 72, mixed: 16, negative: 12, status: "Strong" },
    { area: "Team Climate & Safety", positive: 70, mixed: 18, negative: 12, status: "Strong" },
    { area: "Value & Focus", positive: 41, mixed: 35, negative: 24, status: "Watch" },
    { area: "Ownership & Empowerment", positive: 55, mixed: 28, negative: 17, status: "Watch" },
    { area: "Collaboration & Support", positive: 52, mixed: 27, negative: 21, status: "Watch" },
    { area: "Ways of Working", positive: 49, mixed: 29, negative: 22, status: "Concern" },
    { area: "Workload & Sustainability", positive: 38, mixed: 24, negative: 38, status: "Concern" },
  ],
  roleSplit: [
    {
      area: "Direction & Priorities",
      pm: 4.1,
      pd: 3.7,
      shared: 3.8,
      gap: 0.4,
      gapFlag: false,
    },
    {
      area: "Value & Focus",
      pm: 3.8,
      pd: 3.3,
      shared: 3.4,
      gap: 0.5,
      gapFlag: false,
    },
    {
      area: "Ownership & Empowerment",
      pm: 3.7,
      pd: 3.0,
      shared: 3.4,
      gap: 0.7,
      gapFlag: true,
    },
    {
      area: "Ways of Working",
      pm: 3.4,
      pd: 3.0,
      shared: 3.2,
      gap: 0.4,
      gapFlag: false,
    },
    {
      area: "Collaboration & Support",
      pm: 3.5,
      pd: 3.1,
      shared: 3.2,
      gap: 0.4,
      gapFlag: false,
    },
    {
      area: "Workload & Sustainability",
      pm: 3.1,
      pd: 2.5,
      shared: 2.8,
      gap: 0.6,
      gapFlag: false,
    },
    {
      area: "Team Climate & Safety",
      pm: 4.5,
      pd: 3.7,
      shared: 3.8,
      gap: 0.3,
      gapFlag: false,
    },
  ],
  emergingThemes: [
    {
      theme: "Workload Balance",
      mentions: 12,
      recurrence: 3,
      response: "Review sprint capacity and backlog prioritisation",
    },
    {
      theme: "Direction Clarity",
      mentions: 8,
      recurrence: 2,
      response: "Increase frequency of team-level goal reviews",
    },
    {
      theme: "Recognition",
      mentions: 6,
      recurrence: 1,
      response: "Implement monthly recognition moments in team standup",
    },
  ],
  leadershipActions: [
    {
      action: "Review sprint capacity planning",
      focusArea: "Workload & Sustainability",
      started: "Apr '26",
      owner: "Eng Lead",
      status: "In Progress",
    },
    {
      action: "Monthly OKR review with full team",
      focusArea: "Direction & Priorities",
      started: "Jun '26",
      owner: "Product Manager",
      status: "Planned",
    },
    {
      action: "Team retrospective workshop",
      focusArea: "Team Climate & Safety",
      started: "Feb '26",
      owner: "Scrum Master",
      status: "Completed",
    },
  ],
}

export type SentimentStatus = "Strong" | "Watch" | "Concern" | "Stable"
export type ActionStatus = "In Progress" | "Planned" | "Completed"
